site_name: Weather Station Project Documentation
site_url: https://slevasse.github.io/weather_station_doc/

repo_name: GitHub
repo_url: https://github.com/slevasse/weather_station_doc

# ---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–--
theme:
  name: material
  palette:
    primary: 'light green'
    accent: 'light blue'
  feature:
    tabs: true
  icon:
    logo: fontawesome/winter/snowplow
    repo: fontawesome/brands/git-alt
  # Logo from: https://gitlab.cern.ch/acc-models/acc-models-www
  #logo: fontawesome/brands/git-alt
#
extra_css:
  - 'stylesheets/extra.css'
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
#

# ---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–--
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:  
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - pymdownx.arithmatex
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.magiclink
  - pymdownx.details

# ---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–---–--
nav:
  ###################################
  - Home:
    - Welcome: index.md
    - Example Markdown: example-markdown.md
    - Docs Information: docs-info.md
  ###################################
  - Node:
    - Requirements: node/city-node-requirement-specs.md
    - Hardware overview: node/city-node-hardware.md
    - Modules:
      - SDS1011: node/city-node-hardware-sds1011.md
    - Software overview: node/city-node-software.md
    - State machine implementation: node/city-node-fsm-implementation.md
    - State implementation:
      - Init state: node/city-node-init-state.md
      - Sleep state: node/city-node-sleep-state.md
      - Measure state: node/city-node-measure-state.md
      - Transmit state: node/city-node-transmit-state.md
      - Save state: node/city-node-save-state.md
      - Error state: node/city-node-error-state.md
  ###################################
  - Server:
    - Requirements and spec: server/server-requirement-specs.md 
    - Hardware: server/server-hardware.md
    - Data server:
      - Options: server/data-server-option.md
      - HDF5 database: server/HDF5-database.md
      - Data server: server/data-server.md
    - Web server: 
      - Setup the pi: server/pi-setup.md